"""add_max_attempts

Revision ID: 6d0c9d88c7bf
Revises: 99371f71fe5a
Create Date: 2025-06-12 00:23:46.761605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0c9d88c7bf'
down_revision: Union[str, None] = '99371f71fe5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluators', sa.Column('max_attempts', sa.Integer(), nullable=True))
    op.alter_column('evaluators', 'is_auto_eval',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluators', 'is_auto_eval',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_column('evaluators', 'max_attempts')
    # ### end Alembic commands ###
